In [1]:
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
df=sns.load_dataset("penguins")

In [6]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [140]:
df.shape

(333, 7)

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            333 non-null    object 
 1   island             333 non-null    object 
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 28.9+ KB


In [142]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [143]:
df.dropna(inplace=True)

In [144]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [145]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [146]:
#One Hot Encoding categorical to numeric
df.sex.unique()


array(['Male', 'Female'], dtype=object)

In [147]:
sex=pd.get_dummies(df["sex"],drop_first=True)

In [148]:
sex.head()

Male
0     1
1     0
2     0
4     0
5     1

In [149]:
df.corr()

bill_length_mm  bill_depth_mm  flipper_length_mm  \
bill_length_mm           1.000000      -0.228626           0.653096   
bill_depth_mm           -0.228626       1.000000          -0.577792   
flipper_length_mm        0.653096      -0.577792           1.000000   
body_mass_g              0.589451      -0.472016           0.872979   

                   body_mass_g  
bill_length_mm        0.589451  
bill_depth_mm        -0.472016  
flipper_length_mm     0.872979  
body_mass_g           1.000000

In [211]:
df.cov()

bill_length_mm  bill_depth_mm  flipper_length_mm  \
bill_length_mm          29.906333      -2.462091          50.058195   
bill_depth_mm           -2.462091       3.877888         -15.947248   
flipper_length_mm       50.058195     -15.947248         196.441677   
body_mass_g           2595.623304    -748.456122        9852.191649   

                     body_mass_g  
bill_length_mm       2595.623304  
bill_depth_mm        -748.456122  
flipper_length_mm    9852.191649  
body_mass_g        648372.487699

In [150]:
df["island"]

0      Torgersen
1      Torgersen
2      Torgersen
4      Torgersen
5      Torgersen
         ...    
338       Biscoe
340       Biscoe
341       Biscoe
342       Biscoe
343       Biscoe
Name: island, Length: 333, dtype: object

In [151]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [152]:
island=pd.get_dummies(df["island"],drop_first=True)

In [153]:
new_data=pd.concat([df,island,sex],axis=1)

In [154]:
new_data=new_data.drop("sex",axis=1)

In [155]:
new_data

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g  Dream  Torgersen  Male  
0         3750.0      0          1     1  
1         3800.0      0          1     0  
2         3250.0      0          1     0  
4         3450.0      0          1     0  
5         3650.0      0          1     1  
..           ...    ...        ...   ...  
338       4925.0      0          0     0  
340       4850.0      0          0     0  
341       5750.0      0          0     1  
342       5200.0      0          0     0  
343       5400.0      0          0     1  

[333 rows x 9 columns]

In [156]:
new_data.drop("island",axis=1,inplace=True)

In [157]:
new_data

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0    Adelie            39.1           18.7              181.0       3750.0   
1    Adelie            39.5           17.4              186.0       3800.0   
2    Adelie            40.3           18.0              195.0       3250.0   
4    Adelie            36.7           19.3              193.0       3450.0   
5    Adelie            39.3           20.6              190.0       3650.0   
..      ...             ...            ...                ...          ...   
338  Gentoo            47.2           13.7              214.0       4925.0   
340  Gentoo            46.8           14.3              215.0       4850.0   
341  Gentoo            50.4           15.7              222.0       5750.0   
342  Gentoo            45.2           14.8              212.0       5200.0   
343  Gentoo            49.9           16.1              213.0       5400.0   

     Dream  Torgersen  Male  
0        0          1     1  
1        0          1     0  
2        0          1     0  
4        0          1     0  
5        0          1     1  
..     ...        ...   ...  
338      0          0     0  
340      0          0     0  
341      0          0     1  
342      0          0     0  
343      0          0     1  

[333 rows x 8 columns]

In [158]:
Y=new_data["species"]

In [159]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [160]:
Y=Y.map({"Adelie":0,"Chinstrap":1,"Gentoo":2})

In [161]:
new_data=new_data.drop("species",axis=1)

In [162]:
X=new_data


In [163]:
from sklearn.model_selection import train_test_split

In [164]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [165]:
Y_test.unique()

array([0, 2, 1])

In [166]:
X_train

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
165            52.0           18.1              201.0       4050.0      1   
156            52.7           19.8              197.0       3725.0      1   
112            39.7           17.7              193.0       3200.0      0   
220            46.1           13.2              211.0       4500.0      0   
96             38.1           18.6              190.0       3700.0      1   
..              ...            ...                ...          ...    ...   
332            43.5           15.2              213.0       4650.0      0   
198            50.1           17.9              190.0       3400.0      1   
123            41.4           18.5              202.0       3875.0      0   
53             42.0           19.5              200.0       4050.0      0   
178            50.5           18.4              200.0       3400.0      1   

     Torgersen  Male  
165          0     1  
156          0     1  
112          0     0  
220          0     0  
96           0     0  
..         ...   ...  
332          0     0  
198          0     0  
123          1     1  
53           0     1  
178          0     0  

[233 rows x 7 columns]

In [200]:
from sklearn.ensemble import RandomForestClassifier
mdl=RandomForestClassifier(n_estimators=7,criterion="gini",random_state=0)

In [201]:
Y_train.shape

(233,)

In [202]:
Y.fillna(0)

0      0
1      0
2      0
4      0
5      0
      ..
338    2
340    2
341    2
342    2
343    2
Name: species, Length: 333, dtype: int64

In [203]:
Y=Y.fillna(0.0)

In [204]:
np.array(Y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [205]:
 mdl.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [206]:
Y_pred=mdl.predict(X_test)
Y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [207]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [208]:
matrix=confusion_matrix(Y_test,Y_pred)

In [209]:
matrix

array([[48,  0,  0],
       [ 1, 15,  0],
       [ 0,  0, 36]])

In [212]:
accuracy_score(Y_test,Y_pred)*100

99.0